const testDeck = [
    { key: 35, suit: 'spades', faceValue: '10', numberValue: '10' },
    { key: 17, suit: 'hearts', faceValue: '5', numberValue: '5' },
    { key: 1, suit: 'diamonds', faceValue: '2', numberValue: '2' },
    { key: 22, suit: 'hearts', faceValue: '10', numberValue: '10' },
    { key: 11, suit: 'diamonds', faceValue: 'Q', numberValue: '10' },
    { key: 49, suit: 'clubs', faceValue: 'J', numberValue: '10' },
    { key: 47, suit: 'clubs', faceValue: '9', numberValue: '9' },
    { key: 42, suit: 'clubs', faceValue: '4', numberValue: '4' },
    { key: 24, suit: 'hearts', faceValue: 'Q', numberValue: '10' },
    { key: 21, suit: 'hearts', faceValue: '9', numberValue: '9' },
    { key: 23, suit: 'hearts', faceValue: 'J', numberValue: '10' },
    { key: 13, suit: 'diamonds', faceValue: 'A', numberValue: '10' },
    { key: 9, suit: 'diamonds', faceValue: '10', numberValue: '10' },
    { key: 52, suit: 'clubs', faceValue: 'A', numberValue: '10' },
    { key: 26, suit: 'hearts', faceValue: 'A', numberValue: '10' },
    { key: 46, suit: 'clubs', faceValue: '8', numberValue: '8' },
    { key: 4, suit: 'diamonds', faceValue: '5', numberValue: '5' },
    { key: 38, suit: 'spades', faceValue: 'K', numberValue: '10' },
    { key: 27, suit: 'spades', faceValue: '2', numberValue: '2' },
    { key: 16, suit: 'hearts', faceValue: '4', numberValue: '4' },
    { key: 43, suit: 'clubs', faceValue: '5', numberValue: '5' },
    { key: 8, suit: 'diamonds', faceValue: '9', numberValue: '9' },
    { key: 45, suit: 'clubs', faceValue: '7', numberValue: '7' },
    { key: 33, suit: 'spades', faceValue: '8', numberValue: '8' },
    { key: 51, suit: 'clubs', faceValue: 'K', numberValue: '10' },
    { key: 34, suit: 'spades', faceValue: '9', numberValue: '9' },
    { key: 44, suit: 'clubs', faceValue: '6', numberValue: '6' },
    { key: 39, suit: 'spades', faceValue: 'A', numberValue: '10' },
    { key: 18, suit: 'hearts', faceValue: '6', numberValue: '6' },
    { key: 37, suit: 'spades', faceValue: 'Q', numberValue: '10' },
    { key: 40, suit: 'clubs', faceValue: '2', numberValue: '2' },
    { key: 20, suit: 'hearts', faceValue: '8', numberValue: '8' },
    { key: 3, suit: 'diamonds', faceValue: '4', numberValue: '4' },
    { key: 32, suit: 'spades', faceValue: '7', numberValue: '7' },
    { key: 31, suit: 'spades', faceValue: '6', numberValue: '6' },
    { key: 10, suit: 'diamonds', faceValue: 'J', numberValue: '10' },
    { key: 36, suit: 'spades', faceValue: 'J', numberValue: '10' },
    { key: 41, suit: 'clubs', faceValue: '3', numberValue: '3' },
    { key: 50, suit: 'clubs', faceValue: 'Q', numberValue: '10' },
    { key: 15, suit: 'hearts', faceValue: '3', numberValue: '3' },
    { key: 14, suit: 'hearts', faceValue: '2', numberValue: '2' },
    { key: 5, suit: 'diamonds', faceValue: '6', numberValue: '6' },
    { key: 6, suit: 'diamonds', faceValue: '7', numberValue: '7' },
    { key: 2, suit: 'diamonds', faceValue: '3', numberValue: '3' },
    { key: 12, suit: 'diamonds', faceValue: 'K', numberValue: '10' },
    { key: 29, suit: 'spades', faceValue: '4', numberValue: '4' },
    { key: 19, suit: 'hearts', faceValue: '7', numberValue: '7' },
    { key: 30, suit: 'spades', faceValue: '5', numberValue: '5' },
    { key: 7, suit: 'diamonds', faceValue: '8', numberValue: '8' },
    { key: 25, suit: 'hearts', faceValue: 'K', numberValue: '10' },
    { key: 48, suit: 'clubs', faceValue: '10', numberValue: '10' },
    { key: 28, suit: 'spades', faceValue: '3', numberValue: '3' }
]

const users = [
    {name:'Bob', password:'password', bank:25000},
    {name:'Amy', password:'test', bank:3000},
    {name:'Terrance', password:'password', bank:10000}
]

export default { testDeck, users }